frontend:
  deploymentname: frontend-deployment
  replicas: 1
  image: 10ajaykumar/frontend:1.0.0
  servicename: frontend-service
  type: LoadBalancer

backend:
  deploymentname: backend-deployment
  replicas: 1
  image: 10ajaykumar/backend:1.0.0
  servicename: backend-service

db:
  secrets:
    name: db-secrets
    username: dmlqYXk=
    password: UGFzc3dvcmQxMjM=
